spring:
  profiles:
    active:
    - dev
---
server:
  port: 8087
spring:
  profiles: dev
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.203.192:3358/cloudplus_login?useUnicode=true&characterEncoding=utf-8
    username: lboc
    password: '@leboke521@'
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

---
server:
  port: 8088
spring:
  profiles: test
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.203.192:3358/cloudplus_login?useUnicode=true&characterEncoding=utf-8
    username: lboc
    password: '@leboke521@'
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://172.24.202.77:10086/eureka,http://172.24.202.79:10087/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
